version: "3.7"

services:
  onedcutter-db:
    image: mysql:latest
    container_name: 1dcutter_db
    restart: always
    networks:
      - onedcutter_network
    ports:
      - "3306:3306"
    env_file:
      - .env
    healthcheck:
      interval: 15s
      timeout: 10s
      retries: 3

  onedcutter-back:
    # build:
    #   context: ../1DCutter-Back
    image: chodzi/dev-onedcutter-back:latest
    container_name: 1dcutter_back
    depends_on:
      - onedcutter-db
    networks:
      - onedcutter_network
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - spring.datasource.url=jdbc:mysql://onedcutter-db:3306/onedcutter
    env_file:
      - .env

  onedcutter-front:
    # build: 
    #   context: ../1DCutter-Front
    image: chodzi/dev-onedcutter-front:latest
    container_name: 1dcutter_front
    depends_on:
      - onedcutter-back
    networks:
      - onedcutter_network
    ports:
      - "80:80"
    volumes:
      - "/app/node_modules"
      - ".:/app"

networks:
  onedcutter_network: