version: "3.7"
services:
  onedcutter-front:
    build: ..
    container_name: 1dcutter_front
    #image: docker-angular-cutter:latest
    ports:
      - "80:80"
    networks:
      - onedcutter_network
    volumes:
      - "/app/node_modules"
      - ".:/app"
      
networks:
  onedcutter_network:
